### ISSUE TITLE
ssh-bastion

### ISSUE THREAD

**Issue by alfersi** [a1comms/freepbx-ldap#1]
Hi there,

checking the recommended install procedure, it states:

> cp \<ssh-bastion binary location\> /opt/freepbx-ldap/freepbx-ldap

Is that correct? Is ssh-bastion required to be built? Or should it read freepbx-ldap binary?

Regards

**Comment by iamacarpet** [comment]
@alfersi thanks for letting me know.

No, you are right, it isn't needed, it's just a typo showing that I cheated stealing the README from one of my other repos :).

**Comment by alfersi** [comment]
Hi Samuel,

I'm happy to help. We're rewriting the code to connect to a DB in another
server so that when somebody trapped calls from an emergency lift telephone
the address will show up on the receiving extensions, speeding up the
rescue, so thanks to you!

Best regards,

Albert Ferrer

**Comment by iamacarpet** [comment]
Sounds very cool, glad to have helped :).

Please give us a shout if you need a hand, it sounds like something we can add fairly quickly.

Or if you are quite happy doing it yourselves, we’d love to accept a PR with the changes!

I think for inclusion, we’d prefer to see the DB config via environment variables, if you are going this route, as it would allow a Kubernetes friendly workflow.

**Comment by akinto2006** [comment]
Can you detail install procedures step by step for newbies?

I tried to do the recommended install but I end up with a file not found error. Did on a VM the go build but it said can't load package expected package, found <

**Comment by iamacarpet** [comment]
@akinto2006 check the [releases page](https://github.com/a1comms/freepbx-ldap/releases) as it includes a pre-built binary, which you can use for the install procedure in the README file.

**Comment by akinto2006** [comment]
Hi. Appreciate the quick reply. Here is my output.

[image: image.png]

Used WinSCP to transfer the file.

What I did:

1. Downloaded freepbx-ldap.linux.amd64
2. Created /opt/freepbx.ldap directory
3. Copied freepbx-ldap.linux.amd64 to /opt/freepbx-ldap and renamed file to
freepbx-ldap
4. Ran chown -R asterisk:asterisk /opt/freepbx-ldap
5. Downloaded freepbx-ldap.service and copied to /etc/systemd/system/
6. Ran systemctl daemon-reload
7. Ran systemctl enable freepbx-ldap
---Got an error from here---

**Comment by iamacarpet** [comment]
Your image didn’t come through, but the issue is probably the missing chmod to make it executable.

I’ve updated the README

Can you try again and see if that fixes it please?

**Comment by akinto2006** [comment]
Here is the result:


[root@freepbx ~]# cd /opt/freepbx-ldap
[root@freepbx freepbx-ldap]# chmod +x /opt/freepbx-ldap/freepbx-ldap
[root@freepbx freepbx-ldap]# systemctl daemon-reload
[root@freepbx freepbx-ldap]# systemctl enable freepbx-ldap
Failed to execute operation: Bad message
[root@freepbx freepbx-ldap]# chown -R asterisk:asterisk /opt/freepbx-ldap
[root@freepbx freepbx-ldap]# chmod +x /opt/freepbx-ldap/freepbx-ldap
[root@freepbx freepbx-ldap]# systemctl daemon-reload
[root@freepbx freepbx-ldap]# systemctl enable freepbx-ldap
Failed to execute operation: Bad message

**Comment by akinto2006** [comment]
Tried start instead of enable and looked at the log and this is the output.

Jul 31 11:00:51 freepbx.actsi.local systemd[1]:
[/etc/systemd/system/freepbx-ldap.service:83] Assignment outside of
section. Ignoring.
Jul 31 11:00:51 freepbx.actsi.local systemd[1]:
[/etc/systemd/system/freepbx-ldap.service:85] Assignment outside of
section. Ignoring.
Jul 31 11:00:51 freepbx.actsi.local systemd[1]:
[/etc/systemd/system/freepbx-ldap.service:87] Assignment outside of
section. Ignoring.
Jul 31 11:00:51 freepbx.actsi.local systemd[1]:
[/etc/systemd/system/freepbx-ldap.service:90] Assignment outside of
section. Ignoring.
Jul 31 11:00:51 freepbx.actsi.local systemd[1]:
[/etc/systemd/system/freepbx-ldap.service:93] Assignment outside of
section. Ignoring.
Jul 31 11:00:51 freepbx.actsi.local systemd[1]:
[/etc/systemd/system/freepbx-ldap.service:95] Assignment outside of
section. Ignoring.
Jul 31 11:00:51 freepbx.actsi.local systemd[1]:
[/etc/systemd/system/freepbx-ldap.service:97] Assignment outside of
section. Ignoring.
Jul 31 11:00:51 freepbx.actsi.local systemd[1]:
[/etc/systemd/system/freepbx-ldap.service:98] Assignment outside of
section. Ignoring.
Jul 31 11:00:51 freepbx.actsi.local systemd[1]: freepbx-ldap.service lacks
both ExecStart= and ExecStop= setting. Refusing.
Jul 31 11:01:04 freepbx.actsi.local systemd[1]: freepbx-ldap.service lacks
both ExecStart= and ExecStop= setting. Refusing.

**Comment by iamacarpet** [comment]
@akinto2006 only thing I can suggest is to check the contents of the ".service" file. Does it looks the same as what is in this repo?

If you transferred it from Windows, have you tried "dos2unix", to see if it is line ending related?

Otherwise, I'm not sure I can help - it works for us and we don't officially provide support, especially around installation - I can only wish you luck in figuring it out.

**Comment by akinto2006** [comment]
Got it working. You were right. the .service file was wrong. I did a wget
on the server and moved the file to were its supposed to be.
